before_script:
  - docker info

build_image:
  script:
    - docker build -t bldr-docker-registry.lab.lineratesystems.com:5000/talley/f5-service-router:build$CI_BUILD_ID .
    - docker push bldr-docker-registry.lab.lineratesystems.com:5000/talley/f5-service-router:build$CI_BUILD_ID
  tags: 
    - docker-build
